services:
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    build:
      context: "."
      dockerfile: "./mysql/Dockerfile"
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/init.d/:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
