version: "3.1"

services:
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    build:
      context: "."
      dockerfile: "Dockerfile" # .gitignore
    volumes:
      - ./conf.d/:/etc/mysql/conf.d/
      - ./init.d/:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
