services:
  app:
    container_name: app
    ports:
      - "8888:8080"
    build:
      context: .
      dockerfile: ./app/DockerFile
    depends_on:
      - mysql
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    build:
      context: "."
      dockerfile: "./mysql/Dockerfile"
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/init.d/:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
